// Study Guide Knowledge Base - Survey of China (Fall 2025 Edition)
// Expanded to maximize training. Includes comprehensive feedback for every question.

const knowledgeBase = {
    tf: [
        // Geography, Demographics & Symbols
        { ref: "[Point 1]", q: "China's terrain features a 'Three-step' altitude gradient that is low in the west and high in the east.", a: false, exp: "It is HIGH in the west (Qinghai-Tibet Plateau, first step) and LOW in the east (plains and coastal areas, third step)." },
        { ref: "[Point 1]", q: "Mountainous and plateau areas account for over 60% of China's total land area.", a: true, exp: "China has highly diverse landforms, but mountains and plateaus dominate the landscape, accounting for over 60%." },
        { ref: "[Point 4]", q: "China has 5 Special Administrative Regions (SARs) and 2 Autonomous Regions.", a: false, exp: "China has 5 Autonomous Regions (Inner Mongolia, Guangxi, Tibet, Ningxia, Xinjiang) and 2 Special Administrative Regions (Hong Kong, Macao)." },
        { ref: "[Point 5]", q: "The Yellow River is the longest river in China.", a: false, exp: "The Yangtze River is the longest in China. The Yellow River is known as the 'Mother River' of China." },
        { ref: "[Point 7]", q: "On the Chinese national flag, the five yellow stars represent the five major ethnic groups.", a: false, exp: "The five yellow stars represent the unity of the Chinese people under the leadership of the Communist Party of China. The red symbolizes revolution." },
        
        // History, Philosophy & Culture
        { ref: "[Point 10]", q: "Laozi is the founder of Taoism and his core ideas include 'wu-wei' (non-action) and harmony with nature.", a: true, exp: "Laozi emphasized simplicity, humility, and the 'Tao' (the way of nature) during the late Spring and Autumn period." },
        { ref: "[Point 13]", q: "The site of the earliest Chinese civilization is represented by the Xia Dynasty in the Yellow River basin.", a: true, exp: "The earliest civilization sites include Erlitou (Yanshi, Henan), representing the Xia Dynasty." },
        { ref: "[Point 15]", q: "Traditional Chinese architecture completely ignores natural surroundings to emphasize human dominance.", a: false, exp: "It emphasizes the exact opposite: 'harmony between humans and nature', alignment with natural surroundings, and symmetry/balance (north-south axis)." },
        { ref: "[Point 18]", q: "According to the study guide, Cang Jie is known as the Chinese character sage.", a: true, exp: "Cang Jie (仓颉) is traditionally credited with creating Chinese characters." },
        { ref: "[Point 23]", q: "The four basic skills expected of an ancient Chinese scholar are Qin (Music), Qi (Board Games), Shu (Calligraphy), and Hua (Painting).", a: true, exp: "These four skills (Qin, Qi, Shu, Hua) were the ultimate marks of a refined, educated person in ancient China." },
        { ref: "[Point 25]", q: "The Qipao is a traditional clothing style that originated during the Han Dynasty.", a: false, exp: "The Qipao (Cheongsam) evolved from Manchu women's clothing in the late Qing Dynasty, highlighting a fitted silhouette." },
        { ref: "[Point 27]", q: "Face-changing and fire-breathing are stunts specifically belonging to Sichuan Opera.", a: true, exp: "These are dramatic techniques used in Sichuan Opera to express sudden emotions or character transformations." },
        { ref: "[Point 36]", q: "The term 'Kungfu' is more generic than 'Wushu'.", a: false, exp: "'Wushu' (武术) is more generic. It literally means 'martial art' and is the all-encompassing term for all Chinese martial arts." },
        
        // Science, Education & Policy
        { ref: "[Point 39]", q: "There are 24 solar terms (Jieqi) in one traditional Chinese lunar year.", a: true, exp: "The 24 solar terms mark the Sun's position and reflect annual climate changes to guide agriculture." },
        { ref: "[Point 45]", q: "The astronomer Zu Chongzhi created the Daming Calendar in the 5th century.", a: true, exp: "Zu Chongzhi was a brilliant astronomer and mathematician who created the highly accurate Daming Calendar." },
        { ref: "[Point 50]", q: "The title for the person who ranked first in the ancient imperial exam was 'Zhuangyuan' (状元).", a: true, exp: "The 'Zhuangyuan' was the top scholar in the highest level of the imperial examination system." },
        { ref: "[Point 55]", q: "The '985 Project' aims to build 100 first-class universities for the 21st century.", a: false, exp: "The '211 Project' aimed at 100 universities for the 21st century. The '985 Project' focused on building a smaller number of world-class, internationally renowned research universities." },
        { ref: "[Point 60]", q: "Since 1978, China has maintained an average annual economic growth rate of about 9% for decades.", a: true, exp: "Thanks to the Reform and Opening-up policy, China achieved sustained high economic growth, lifting hundreds of millions out of poverty." },
        { ref: "[Point 61]", q: "Chinese modernization strongly encourages developing nations to completely copy its economic model.", a: false, exp: "The guide states that each country has unique national conditions, so experiences should be ADAPTED rather than copied." },
        { ref: "[Point 68]", q: "China participates in UN peacekeeping operations and mediates international disputes, such as the Iran-Saudi Arabia reconciliation.", a: true, exp: "These are key examples of China's contributions to maintaining world peace and advocating multilateralism." }
    ],
    mc: [
        // Geography & Basic Facts
        { ref: "[Point 2]", q: "What is the approximate land area of China?", options: ["7.6 million sq km", "9.6 million sq km (3.7 million sq miles)", "12 million sq km", "14.1 million sq km"], answer: 1 },
        { ref: "[Point 9]", q: "Which of the following is TRUE about Sichuan province?", options: ["Its capital is Chongqing.", "It is located in Northeast China.", "It features the Wuhou Temple dedicated to Zhuge Liang.", "It is the least populated province in China."], answer: 2 },
        { ref: "[Point 12]", q: "How many officially recognized ethnic groups are there in China, and which is the largest?", options: ["55; Tibetan", "56; Han", "34; Zhuang", "56; Manchu"], answer: 1 },
        
        // History & Philosophy
        { ref: "[Point 10]", q: "Which philosopher advocated ruling by virtue and education for all, with core ideas including 'benevolence' (ren) and 'propriety' (li)?", options: ["Laozi", "Zhuangzi", "Confucius", "Han Feizi"], answer: 2 },
        { ref: "[Point 11]", q: "During the 'Hundred Schools of Thought', which school advocated for strict laws and harsh punishments to control people?", options: ["Confucianism", "Daoism", "Legalism", "Mohism"], answer: 2 },
        { ref: "[Point 16]", q: "Who was Zheng He?", options: ["The first emperor of the Qin Dynasty", "A navigator and diplomat of the Ming Dynasty who led seven maritime expeditions", "The inventor of papermaking", "The author of 'The Art of War'"], answer: 1 },
        { ref: "[Point 19]", q: "Which of the following is NOT one of the Four Famous Ancient Chinese Novels?", options: ["Romance of the Three Kingdoms", "Water Margin", "The Art of War", "Dream of the Red Chamber"], answer: 2 },
        { ref: "[Point 26]", q: "In Beijing Opera, what does the role 'Jing' (净) represent?", options: ["Male roles", "Female roles", "Painted-face male roles", "Comic male roles"], answer: 2 },
        { ref: "[Point 28]", q: "Who is known as the 'Poetry Sage' (诗圣) of the Tang Dynasty, famous for his realistic poems?", options: ["Li Bai", "Wang Wei", "Du Fu", "Bai Juyi"], answer: 2 },
        { ref: "[Point 31]", q: "Which emperor standardized writing, currency, and measurements, and is buried with the Terracotta Army?", options: ["Emperor Wu of Han", "Wu Zetian", "Qin Shi Huang", "Kublai Khan"], answer: 2 },
        { ref: "[Point 32]", q: "Who was the first and only female emperor in Chinese history?", options: ["Cixi", "Wu Zetian", "Wang Zhaojun", "Yang Guifei"], answer: 1 },
        { ref: "[Point 35]", q: "Which city is known as the capital of the Six Dynasties and the early Ming dynasty?", options: ["Xi'an", "Luoyang", "Nanjing", "Beijing"], answer: 2 },

        // Science, Medicine & Society
        { ref: "[Point 41]", q: "Which of the following represents China's ancient 'Four Great Inventions'?", options: ["Silk, Porcelain, Tea, Iron casting", "Compass, Gunpowder, Papermaking, Printing", "Abacus, Seismograph, Acupuncture, Calligraphy", "Paper money, Movable type, Crossbow, Bronze"], answer: 1 },
        { ref: "[Point 42]", q: "In Traditional Chinese Medicine (TCM), which of the following represents the four diagnosis methods?", options: ["Blood test, X-ray, Surgery, Medication", "Inspection, Auscultation & Olfaction, Inquiry, Palpation", "Acupuncture, Cupping, Massage, Diet", "Yin, Yang, Qi, Blood"], answer: 1 },
        { ref: "[Point 47]", q: "Why was Catholicism prohibited in China during the Ming/Qing transition?", options: ["Because of the Opium War", "Due to the Rites Controversy over Chinese converts continuing Confucian ancestral rites", "Because Marco Polo advised against it", "Due to a lack of translated Bibles"], answer: 1 },
        { ref: "[Point 49]", q: "Which of the following is considered one of the 'Eight Great Cuisines' of China?", options: ["Beijing Cuisine", "Sichuan Cuisine", "Shanghai Cuisine", "Shaanxi Cuisine"], answer: 1 },
        { ref: "[Point 54]", q: "Which of the following is a favorable policy for students of minority ethnic groups?", options: ["Mandatory military service", "Higher Gaokao score requirements", "Bilingual education (mother tongue + Mandarin)", "Exclusion from public universities"], answer: 2 },
        
        // Politics & Modern Development
        { ref: "[Point 56]", q: "What is the political party system of China called?", options: ["Two-party democratic system", "Multi-party cooperation and political consultation system under CPC leadership", "Constitutional monarchy", "Single-party absolute dictatorship without consultation"], answer: 1 },
        { ref: "[Point 58]", q: "What is the purpose of China's 'Grain for Green' project?", options: ["To maximize wheat production", "To convert farmland back to forests/grasslands to prevent soil erosion", "To export grain to foreign countries", "To build cities on agricultural land"], answer: 1 },
        { ref: "[Point 62]", q: "When was the 'Reform and Opening-up' policy launched by Deng Xiaoping?", options: ["1949", "1978", "2001", "2013"], answer: 1 },
        { ref: "[Point 64]", q: "What does the 'One Belt and One Road' Initiative aim to do?", options: ["Build a physical wall around China", "Promote international cooperation through infrastructure, trade, and cultural exchanges", "Export Chinese political systems to Europe", "Restrict global trade to Asia only"], answer: 1 },
        { ref: "[Point 69]", q: "In what year did China shift to a 'three-child policy' to address the aging population?", options: ["1970", "2016", "2021", "2024"], answer: 2 }
    ],
    def: [
        { ref: "[Point 11]", term: "Mohism", def: "A school during the 'Hundred Schools of Thought' period that advocated for impartial care for all (universal love) and practical utility." },
        { ref: "[Point 21]", term: "Main principle of Shanshui painting", def: "Capturing the spirit through form (yi spirit as the core, emphasizing artistic conception over realistic detail) and reflecting the Harmony between Humanity and Nature." },
        { ref: "[Point 25]", term: "Zhongshanzhuang (Zhongshan Suit)", def: "A clothing style designed based on Sun Yat-sen’s ideas. It symbolizes modernization and patriotism, featuring a simple and practical style." },
        { ref: "[Point 38]", term: "H&T chronology (干支纪年法)", def: "Heavenly Stems and Earthly Branches (gānzhī). It is China's traditional 60-year cyclical calendar system used to mark years, months, days, and hours." },
        { ref: "[Point 46]", term: "Marco Polo", def: "A Venetian merchant and explorer who traveled to China in the 13th century, served under Kublai Khan's Yuan Dynasty for 17 years, and wrote a book introducing Europeans to the wealth and culture of the East." },
        { ref: "[Point 53]", term: "University Certificates in China", def: "Graduation certificate (proving completion of academic requirements) and Degree certificate (proving achievement of a certain academic level, e.g., bachelor’s)." },
        { ref: "[Point 59]", term: "Five principles of peaceful coexistence", def: "Proposed in the 1950s: 1) Mutual respect for sovereignty and territorial integrity, 2) Mutual non-aggression, 3) Non-interference in internal affairs, 4) Equality and mutual benefit, 5) Peaceful coexistence." },
        { ref: "[Point 61]", term: "Chinese modernization", def: "A modernization path featuring a large population, common prosperity for all, harmony between humans and nature, and peaceful development, differing from Western modernization models." },
        { ref: "[Point 65]", term: "Community with a Shared Future for Mankind", def: "A foreign policy concept emphasizing that all countries are interdependent. It advocates mutual respect, equity, and win-win cooperation to address global challenges like climate change and poverty." },
        { ref: "[Point 66]", term: "System of Regional Ethnic Autonomy", def: "A basic political system where areas with concentrated ethnic minorities establish autonomous regions/prefectures to exercise rights to manage local affairs and develop their own cultures and economies." },
        { ref: "[Point 67]", term: "Socialism with Chinese characteristics", def: "A development path combining Marxist principles with China’s national conditions, emphasizing CPC leadership, public ownership dominance, common prosperity, and integrating a market economy with government regulation." }
    ],
    exp: [
        { ref: "[Point 1]", q: "What are the main characteristics of China’s terrain?", ans: "1) Diverse landforms: Includes mountains, plateaus, basins, plains, and hills. 2) 'Three-step' altitude gradient: High in the west (Qinghai-Tibet Plateau) and low in the east (plains/coastal areas). 3) Mountainous and plateau areas account for over 60% of the total land area." },
        { ref: "[Point 9]", q: "Provide the basic facts of Sichuan province (Capital, Location, Dialect, Famous Mountains, and Wuhouci).", ans: "Capital: Chengdu. Location: Southwest China, upper Yangtze. Dialect: Sichuanese (Southwestern Mandarin). Mountains: Mount Emei (sacred Buddhist mountain). Wuhou Temple: A shrine in Chengdu dedicated to Zhuge Liang, a revered strategist from the Three Kingdoms period." },
        { ref: "[Point 10]", q: "Compare the basic facts and core ideas of Confucius and Laozi.", ans: "Confucius (founder of Confucianism) advocated ruling by virtue, 'benevolence' (ren), 'propriety' (li), and harmony. Laozi (founder of Taoism) emphasized the 'Tao' (way of nature), 'non-action' (wu-wei), simplicity, humility, and harmony with nature." },
        { ref: "[Point 15]", q: "Traditionally, what ideas are observed when planning buildings and architecture in China?", ans: "The ideas of 'harmony between humans and nature' and 'symmetry and balance'. This emphasizes alignment with natural surroundings, hierarchical layout along a north-south axis, and the integration of function with aesthetics." },
        { ref: "[Point 22]", q: "What are the four essential elements of traditional Chinese painting?", ans: "1) Brushwork (笔), 2) Ink (墨), 3) Paper or Silk (纸), and 4) Color (彩)." },
        { ref: "[Point 31]", q: "What were Qin Shi Huang's main contributions to Chinese history?", ans: "He was the first emperor to unify China in 221 BCE. He unified the country politically and culturally, standardized writing, currency, and measurements, and built the early Great Wall and road networks. His legacy includes the Terracotta Army and bronze chariots." },
        { ref: "[Point 40]", q: "Name three important festivals in China and their typical customs.", ans: "1) Chinese New Year (Spring Festival): Family reunion dinner, red envelopes, fireworks. 2) Qingming Festival: Tomb-sweeping and spring outings. 3) Dragon Boat Festival: Eating zongzi and racing dragon boats. 4) Mid-Autumn Festival: Admiring the moon and eating mooncakes." },
        { ref: "[Point 41]", q: "What are the main contributions of science and technology of China in history and today?", ans: "Ancient: The Four Great Inventions (Compass, gunpowder, papermaking, printing), plus silk and porcelain. Modern: 5G tech (Huawei), high-speed rail, e-commerce, space exploration (Lunar Chang'e, Tiangong station), and renewable energy infrastructure." },
        { ref: "[Point 51]", q: "Explain the origin and functions of the Great Wall.", ans: "Origin: First built during the Spring/Autumn and Warring States periods, then unified and expanded by Qinshihuang. Functions: Military defense against nomadic invasions, border management (trade/population control), and a symbol of national unity." },
        { ref: "[Point 52]", q: "Why did tea become the drink for scholar-officials in ancient China?", ans: "1) It has a refreshing effect that helps with reading and meditation. 2) Tea culture emphasizes elegance and tranquility, aligning with scholars' pursuit of moral integrity. 3) Tea ceremonies became a social activity to exchange ideas." },
        { ref: "[Point 57]", q: "What are the advantages of the Chinese political system over the western style democracy system?", ans: "It focuses on overall national interests and long-term development (avoiding short-term political gains), allows for highly efficient decision-making (mobilizing resources for major projects), and provides full representation of people's interests through extensive political consultation." },
        { ref: "[Point 60]", q: "What are China’s economic achievements after 1978 and the reasons behind them?", ans: "Achievements: Sustained ~9% annual growth, becoming the 2nd largest economy, massive poverty alleviation, and rapid infrastructure development. Reasons: The Reform and Opening-up policy, stable political environment, large labor force/market, and scientific macro-control by the government." },
        { ref: "[Point 62]", q: "What is the 'Reform and Opening-up' policy of China?", ans: "Launched in 1978 by Deng Xiaoping. 'Reform' shifted the system from a planned economy to a socialist market economy. 'Opening-up' referred to opening coastal cities and regions to foreign investment, trade, and technology exchange." },
        { ref: "[Point 69]", q: "How does the evolution of China’s family planning policy reflect the principles upheld by the government?", ans: "It evolved from the strict 'one-child' policy (1970s) to 'two-child' (2016) and 'three-child' (2021) to address the aging population. This reflects the principles of putting people first, adapting policies based on real national population changes, and pursuing long-term sustainable development." }
    ]
};